<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'api#getBootstrap', 'url' => '/api/bootstrap', 'verb' => 'GET'],
		['name' => 'api#createCourse', 'url' => '/api/courses', 'verb' => 'POST'],
		['name' => 'api#updateCourse', 'url' => '/api/courses/{courseId}', 'verb' => 'PUT'],
		['name' => 'api#deleteCourse', 'url' => '/api/courses/{courseId}', 'verb' => 'DELETE'],
		['name' => 'api#deleteCourse', 'url' => '/api/courses/{courseId}/delete', 'verb' => 'POST'],
		['name' => 'api#setCourseDeck', 'url' => '/api/courses/{courseId}/deck', 'verb' => 'PUT'],
		['name' => 'api#createCourseLink', 'url' => '/api/courses/{courseId}/links', 'verb' => 'POST'],
		['name' => 'api#updateCourseLink', 'url' => '/api/links/{linkId}', 'verb' => 'PUT'],
		['name' => 'api#deleteCourseLink', 'url' => '/api/links/{linkId}', 'verb' => 'DELETE'],
		['name' => 'api#deleteCourseLink', 'url' => '/api/links/{linkId}/delete', 'verb' => 'POST'],
		['name' => 'api#createLessonSeries', 'url' => '/api/courses/{courseId}/lesson-series', 'verb' => 'POST'],
		['name' => 'api#createLesson', 'url' => '/api/courses/{courseId}/lessons', 'verb' => 'POST'],
		['name' => 'api#copyLesson', 'url' => '/api/courses/{courseId}/copy-lesson', 'verb' => 'POST'],
		['name' => 'api#updateLesson', 'url' => '/api/lessons/{lessonId}', 'verb' => 'PUT'],
		['name' => 'api#deleteLesson', 'url' => '/api/lessons/{lessonId}', 'verb' => 'DELETE'],
		['name' => 'api#deleteLesson', 'url' => '/api/lessons/{lessonId}/delete', 'verb' => 'POST'],
		['name' => 'api#createLessonItem', 'url' => '/api/lessons/{lessonId}/items', 'verb' => 'POST'],
		['name' => 'api#reorderLessonItems', 'url' => '/api/lessons/{lessonId}/items/reorder', 'verb' => 'POST'],
		['name' => 'api#moveLessonItem', 'url' => '/api/items/{itemId}/move', 'verb' => 'POST'],
		['name' => 'api#updateLessonItem', 'url' => '/api/items/{itemId}', 'verb' => 'PUT'],
		['name' => 'api#deleteLessonItem', 'url' => '/api/items/{itemId}', 'verb' => 'DELETE'],
		['name' => 'api#deleteLessonItem', 'url' => '/api/items/{itemId}/delete', 'verb' => 'POST'],
		['name' => 'api#uploadAttachment', 'url' => '/api/items/{itemId}/attachments', 'verb' => 'POST'],
		['name' => 'api#getParticipation', 'url' => '/api/lessons/{lessonId}/participation', 'verb' => 'GET'],
		['name' => 'api#saveParticipation', 'url' => '/api/lessons/{lessonId}/participation', 'verb' => 'POST'],
		['name' => 'api#getParticipationOverview', 'url' => '/api/courses/{courseId}/participation', 'verb' => 'GET'],
		['name' => 'api#getStudents', 'url' => '/api/courses/{courseId}/students', 'verb' => 'GET'],
		['name' => 'api#createStudent', 'url' => '/api/courses/{courseId}/students', 'verb' => 'POST'],
		['name' => 'api#importStudents', 'url' => '/api/courses/{courseId}/students/import', 'verb' => 'POST'],
		['name' => 'api#updateStudent', 'url' => '/api/students/{studentId}', 'verb' => 'PUT'],
		['name' => 'api#deleteStudent', 'url' => '/api/students/{studentId}', 'verb' => 'DELETE'],
		['name' => 'api#deleteStudent', 'url' => '/api/students/{studentId}/delete', 'verb' => 'POST'],
		['name' => 'api#createStudentGroup', 'url' => '/api/courses/{courseId}/student-groups', 'verb' => 'POST'],
		['name' => 'api#updateStudentGroup', 'url' => '/api/student-groups/{groupId}', 'verb' => 'PUT'],
		['name' => 'api#deleteStudentGroup', 'url' => '/api/student-groups/{groupId}', 'verb' => 'DELETE'],
		['name' => 'api#deleteStudentGroup', 'url' => '/api/student-groups/{groupId}/delete', 'verb' => 'POST'],
		['name' => 'api#exportCoursePlan', 'url' => '/api/courses/{courseId}/plan', 'verb' => 'GET'],
		['name' => 'api#previewCoursePlan', 'url' => '/api/courses/{courseId}/plan/preview', 'verb' => 'POST'],
		['name' => 'api#importCoursePlan', 'url' => '/api/courses/{courseId}/plan/import', 'verb' => 'POST'],
		['name' => 'api#previewPlanFromFolder', 'url' => '/api/courses/{courseId}/plan/folder/preview', 'verb' => 'POST'],
		['name' => 'api#importPlanFromFolder', 'url' => '/api/courses/{courseId}/plan/folder/import', 'verb' => 'POST'],
		['name' => 'api#saveSettings', 'url' => '/api/settings', 'verb' => 'PUT'],
		['name' => 'api#exportData', 'url' => '/api/export', 'verb' => 'GET'],
		['name' => 'api#exportData', 'url' => '/api/export', 'verb' => 'POST'],
		['name' => 'api#importData', 'url' => '/api/import', 'verb' => 'POST'],
		['name' => 'api#publishCourse', 'url' => '/api/courses/{courseId}/publish', 'verb' => 'POST'],
	],
];
